// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID                             string `gorm:"column:id;primaryKey" json:"id"`
	Username                       string `gorm:"column:username;comment:用户名" json:"username"`              // 用户名
	Password                       string `gorm:"column:password;comment:密码，MD5加密" json:"password"`         // 密码，MD5加密
	PasswordSm3                    string `gorm:"column:password_sm3;comment:密码，SM3加密" json:"password_sm3"` // 密码，SM3加密
	Name                           string `gorm:"column:name" json:"name"`
	CreateTime                     int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                                                             // 创建时间
	LatestLoginTime                int64  `gorm:"column:latest_login_time;comment:最近一次登录时间" json:"latest_login_time"`                                                             // 最近一次登录时间
	PasswordChangeTime             int64  `gorm:"column:password_change_time;comment:修改密码时间" json:"password_change_time"`                                                         // 修改密码时间
	Status                         int32  `gorm:"column:status;not null;default:1;comment:0:正常|1:第一次登录|2:密码过期" json:"status"`                                                     // 0:正常|1:第一次登录|2:密码过期
	RoleID                         int32  `gorm:"column:role_id;comment:角色id" json:"role_id"`                                                                                     // 角色id
	Classification                 int32  `gorm:"column:classification;not null;default:1;comment:用户分类 0：系统内置用户|1：自定义用户" json:"classification"`                                   // 用户分类 0：系统内置用户|1：自定义用户
	GatherType                     int32  `gorm:"column:gather_type;default:1;comment:告警视角，默认按照事件名称聚合" json:"gather_type"`                                                        // 告警视角，默认按照事件名称聚合
	PlatformSha256Pass             string `gorm:"column:platform_sha256_pass;comment:平台共用的sha256加密后的密码" json:"platform_sha256_pass"`                                              // 平台共用的sha256加密后的密码
	IsLock                         int32  `gorm:"column:is_lock;not null;comment:当前用户是否被锁定" json:"is_lock"`                                                                       // 当前用户是否被锁定
	OtpSn                          string `gorm:"column:otp_sn;comment:otp令牌的序列号" json:"otp_sn"`                                                                                  // otp令牌的序列号
	MdsPass                        string `gorm:"column:mds_pass;comment:MDS平台密码" json:"mds_pass"`                                                                                // MDS平台密码
	CloudPass                      string `gorm:"column:cloud_pass;comment:云平台规范格式的密码" json:"cloud_pass"`                                                                         // 云平台规范格式的密码
	RadiusServerID                 int32  `gorm:"column:radius_server_id;comment:radius认证服务器ID" json:"radius_server_id"`                                                          // radius认证服务器ID
	AllowOperationModuleIds        string `gorm:"column:allow_operation_module_ids;comment:允许操作的功能模块id，多个逗号分割" json:"allow_operation_module_ids"`                                 // 允许操作的功能模块id，多个逗号分割
	AllowOperationModuleExpireTime int64  `gorm:"column:allow_operation_module_expire_time;not null;comment:允许操作的功能模块限期过期时间，为0则代表永不过期" json:"allow_operation_module_expire_time"` // 允许操作的功能模块限期过期时间，为0则代表永不过期
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
