// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package user

// TableNameUser 是 User 表名常量。
const TableNameUser = "user"

// User 是 user 表的 gorm 映射实体。
// 通过 tools/gen 从数据库自动生成，禁止手动修改此文件。
type User struct {
	ID                             string `gorm:"column:id;primaryKey" json:"id"`
	Username                       string `gorm:"column:username;comment:用户名" json:"username"`
	Password                       string `gorm:"column:password;comment:密码，MD5加密" json:"password"`
	PasswordSm3                    string `gorm:"column:password_sm3;comment:密码，SM3加密" json:"password_sm3"`
	Name                           string `gorm:"column:name" json:"name"`
	CreateTime                     int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`
	LatestLoginTime                int64  `gorm:"column:latest_login_time;comment:最近一次登录时间" json:"latest_login_time"`
	PasswordChangeTime             int64  `gorm:"column:password_change_time;comment:修改密码时间" json:"password_change_time"`
	Status                         int32  `gorm:"column:status;not null;default:1;comment:0:正常|1:第一次登录|2:密码过期" json:"status"`
	RoleID                         int32  `gorm:"column:role_id;comment:角色id" json:"role_id"`
	Classification                 int32  `gorm:"column:classification;not null;default:1;comment:用户分类 0:系统内置用户|1:自定义用户" json:"classification"`
	GatherType                     int32  `gorm:"column:gather_type;default:1;comment:告警视角，默认按照事件名称聚合" json:"gather_type"`
	PlatformSha256Pass             string `gorm:"column:platform_sha256_pass;comment:平台共用的sha256加密后的密码" json:"platform_sha256_pass"`
	IsLock                         int32  `gorm:"column:is_lock;not null;comment:当前用户是否被锁定" json:"is_lock"`
	OtpSn                          string `gorm:"column:otp_sn;comment:otp令牌的序列号" json:"otp_sn"`
	MdsPass                        string `gorm:"column:mds_pass;comment:MDS平台密码" json:"mds_pass"`
	CloudPass                      string `gorm:"column:cloud_pass;comment:云平台规范格式的密码" json:"cloud_pass"`
	RadiusServerID                 int32  `gorm:"column:radius_server_id;comment:radius认证服务器ID" json:"radius_server_id"`
	AllowOperationModuleIds        string `gorm:"column:allow_operation_module_ids;comment:允许操作的功能模块id，多个逗号分割" json:"allow_operation_module_ids"`
	AllowOperationModuleExpireTime int64  `gorm:"column:allow_operation_module_expire_time;not null;comment:允许操作的功能模块限期过期时间，为0则代表永不过期" json:"allow_operation_module_expire_time"`
}

// TableName 返回 User 对应的数据库表名。
func (*User) TableName() string {
	return TableNameUser
}